import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
  "/* This file is generated by esbuild. Do not edit directly. */";

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: ["obsidian", ...builtins],
  format: "cjs",
  target: "es2018",
  sourcemap: prod ? false : "inline",
  logLevel: "info",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
}

await context.watch();
